vraptor-core/src/main/java/br/com/caelum/vraptor/view/DefaultStatus.java, vraptor-core/src/main/java/br/com/caelum/vraptor/view/Status.java, vraptor-core/src/test/java/br/com/caelum/vraptor/view/DefaultStatusTest.java
=> Support status 500

update-site.sh
This script is intended to be run by a CI server (we already have one configured internally at Caelum). It builds the site from scratch and creates a commit in the `gh-pages` branch. The CI server then pushes it if the build succeeds.
This closes #923.
=> Script to automatically deploy the site

vraptor-site/content/en/docs/one-minute-guide.html, vraptor-site/content/pt/docs/guia-de-1-minuto.html
Just an adjustment to turn the documentation clearest...
=> Just a documentation adjustment.

vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/GsonDeserialization.java, vraptor-core/src/test/java/br/com/caelum/vraptor/serialization/gson/GsonDeserializerTest.java
=> Supporting deserialization for GenericController without root

vraptor-blank-project/pom.xml, vraptor-site/content/en/docs/dependencies-and-prerequisites.html, vraptor-site/content/pt/docs/dependencias-e-pre-requisitos.html
* updating docs removing javax.inject dependency
* removing it from blank project's pom
that because VRaptor core already declare `javax.inject` as `provided` and `weld` 
impl already provide it for servlet containers... so, we can keep it simple for users.
=> updating docs about javax.inject

vraptor-core/src/main/java/br/com/caelum/vraptor/interceptor/ExceptionHandlerInterceptor.java, vraptor-site/content/en/docs/controllers-rest.html, vraptor-site/content/pt/docs/controllers-rest.html
Closes https://github.com/caelum/vraptor4/issues/925
=> adding docs about exception attribute

vraptor-core/src/main/java/br/com/caelum/vraptor/VRaptorException.java, vraptor-core/src/main/java/br/com/caelum/vraptor/cache/CacheException.java, vraptor-core/src/main/java/br/com/caelum/vraptor/validator/DefaultValidationException.java, vraptor-core/src/main/java/br/com/caelum/vraptor/validator/ValidationException.java
All of our exceptions inherit from `VRaptorException`, except for the 3 below.
I'm changing them to inherit it too, to keep the symmetry. What do you think?
=> standardizing the inheritance of our internal exceptions

vraptor-core/src/main/java/br/com/caelum/vraptor/observer/ExecuteMethodExceptionHandler.java, vraptor-core/src/main/java/br/com/caelum/vraptor/validator/Messages.java, vraptor-core/src/main/java/br/com/caelum/vraptor/validator/ValidationFailedException.java, vraptor-core/src/test/java/br/com/caelum/vraptor/observer/ExecuteMethodTest.java, vraptor-core/src/test/java/br/com/caelum/vraptor/validator/MessagesTest.java
As suggested by @lucascs [here](https://github.com/caelum/vraptor4/issues/911#issuecomment-67262416). Closes #911.
It breaks compatibility, but we're going to `4.2` and it'll be very highlighted 
on release notes. I'll add some docs before merging it. What do you think?
=> propagating alternative cause if it's not checked

vraptor-site/content/en/docs/testing-components-and-controllers.html, vraptor-site/content/pt/docs/testando-componentes-e-controllers.html
In the last days, some people asked on Google Groups about how to test a Controller method that just serialize an object.
So, I wrote this little doc about `MockSerializationResult`.
=> Adding docs about MockSerializationResult.

vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/Serializee.java
It'll allow users to easily override this behavior, just like in the use case of #933.
=> relaxing visibility of Serializee getActualType

vraptor-core/src/main/java/br/com/caelum/vraptor/controller/DefaultInvalidInputHandler.java
I'm not sure how it was working until now, since it's a normal scoped proxyable bean.
=> adding no-arg default constructor on InvalidInputHandler

vraptor-core/src/main/java/br/com/caelum/vraptor/environment/DefaultEnvironment.java, vraptor-core/src/test/java/br/com/caelum/vraptor/environment/DefaultEnvironmentTest.java
Fixes #972
This avoid concurrent access that could lead to errors in multithread environments.
@Turini @csokol I believe that we don't need to use the `@PostContruct` because we can do it in `DefaultEnvironment`'s constructor. What do you think about it?
=> loading properties in bean construction

vraptor-core/src/main/java/br/com/caelum/vraptor/view/DefaultRefererResult.java, vraptor-core/src/test/java/br/com/caelum/vraptor/view/DefaultRefererResultTest.java
Relaxing getReferer() visibility to 'protected' in order to unit test it
directly; replacing several test methods for referer check with
redirect/forward with a single method that tests the getReferer()
returned value in various situations
=> Defaultrefererfix

vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/GsonBuilderWrapper.java, vraptor-core/src/test/java/br/com/caelum/vraptor/serialization/gson/GsonBuilderWrapperTest.java, vraptor-core/src/test/java/br/com/caelum/vraptor/serialization/gson/GsonDeserializerTest.java
Possible create Serializers without producers, Before throw a expcetion:
```java
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
at br.com.caelum.vraptor.serialization.gson.GsonBuilderWrapper.getAdapterType(GsonBuilderWrapper.java:99)
at br.com.caelum.vraptor.serialization.gson.GsonBuilderWrapper.create(GsonBuilderWrapper.java:74)
at br.com.caelum.vraptor.serialization.gson.GsonDeserialization.deserialize(GsonDeserialization.java:95)
at br.com.caelum.vraptor.serialization.gson.GsonDeserialization$Proxy$_$$_WeldClientProxy.deserialize(Unknown Source)
at br.com.caelum.vraptor.observer.DeserializingObserver.deserializes(DeserializingObserver.java:96)
```
=> Fix Get Adapters in Proxy Class

vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/DateGsonConverter.java, vraptor-site/content/en/docs/converters.html, vraptor-site/content/pt/docs/conversores.html
Closes https://github.com/caelum/vraptor4/issues/931
=> Allowing to override custom Gson Date pattern

vraptor-core/src/main/java/br/com/caelum/vraptor/interceptor/CustomAcceptsVerifier.java
Because Predicate (from Guava) are annotated with `Nullable` and allow null values.
=> Adding a null check to avoid NPE at CustomAcceptsVerifier

vraptor-core/src/main/java/br/com/caelum/vraptor/core/JstlLocalization.java
Small patch do avoid log exception on missing bundle for base name messages.
=> don't log exception on missing bundle for base name messages

vraptor-core/src/main/java/br/com/caelum/vraptor/core/JstlLocalization.java
Closes https://github.com/caelum/vraptor4/issues/1006
=> improving error message when a bundle is not found

vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/GsonDeserialization.java
IMO there is no reason to this log to be INFO instead of WARN. It's a common use to use JSON without root and it get's the log fully of unused messages.
What do you guys think about it? @Turini @lucascs @garcia-jj
=> changing json without root message from info to warn

vraptor-core/src/main/java/br/com/caelum/vraptor/environment/DefaultEnvironment.java, vraptor-core/src/main/java/br/com/caelum/vraptor/http/iogi/VRaptorInstantiator.java, vraptor-core/src/main/java/br/com/caelum/vraptor/http/route/DefaultParametersControl.java, vraptor-core/src/main/java/br/com/caelum/vraptor/interceptor/FlashInterceptor.java, vraptor-core/src/main/java/br/com/caelum/vraptor/observer/RequestHandlerObserver.java, vraptor-core/src/main/java/br/com/caelum/vraptor/observer/upload/CommonsUploadMultipartObserver.java, vraptor-core/src/main/java/br/com/caelum/vraptor/util/SafeResourceBundle.java, vraptor-core/src/main/java/br/com/caelum/vraptor/view/DefaultRefererResult.java, vraptor-core/src/main/java/br/com/caelum/vraptor/view/LinkToHandler.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1166 - “Exception handlers should preserve the original exception”. You can find more information about the issue here: https://dev.eclipse.org/sonar/rules/show/squid:S1166
Please let me know if you have any questions.
Christian
=> Code Quality Improvement - Exception handlers should preserve the original exception

vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/GsonJSONPSerialization.java, vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/GsonSerializer.java, vraptor-core/src/main/java/br/com/caelum/vraptor/util/test/MockHttpServletResponse.java, vraptor-core/src/main/java/br/com/caelum/vraptor/util/test/MockSerializationResult.java, vraptor-core/src/test/java/br/com/caelum/vraptor/serialization/I18nMessageSerializationTest.java, vraptor-core/src/test/java/br/com/caelum/vraptor/serialization/gson/GsonJSONSerializationTest.java
@Turini @csokol this is related to https://github.com/caelum/vraptor4/issues/1035
=> letting web server commit the response naturally

vraptor-core/src/main/java/br/com/caelum/vraptor/observer/download/DownloadBuilder.java, vraptor-core/src/main/java/br/com/caelum/vraptor/proxy/CDIProxies.java, vraptor-core/src/main/java/br/com/caelum/vraptor/util/StringUtils.java, vraptor-core/src/main/java/br/com/caelum/vraptor/view/Results.java, vraptor-core/src/test/java/br/com/caelum/vraptor/VRaptorMatchers.java, vraptor-core/src/test/java/br/com/caelum/vraptor/interceptor/VRaptorMatchers.java, vraptor-core/src/test/java/br/com/caelum/vraptor/ioc/fixture/HasConstructor.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - Utility classes should not have public constructors
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1118
Please let me know if you have any questions.
M-Ezzat
=> squid:S1118 - Utility classes should not have public constructors

vraptor-core/src/main/java/br/com/caelum/vraptor/validator/Messages.java
Tested with Wildfly using standalone-ha.xml to replicate the http session
=> 'Messages' not serializable error when trying to redirect() using session replication

vraptor-musicjungle/src/main/java/br/com/caelum/vraptor/musicjungle/dao/DefaultMusicDao.java
The vraptor-music-jungle was broken to me. I believe the last refactor forgot remove the variable too. That is right?
=> remove variable before the return

vraptor-core/src/main/java/br/com/caelum/vraptor/core/DefaultConverters.java, vraptor-core/src/test/java/br/com/caelum/vraptor/core/DefaultConvertersTest.java
See [issue 1059](https://github.com/caelum/vraptor4/issues/1059)
=> Consistently handle superclass/subclass converters independent of class load order.

vraptor-core/src/main/java/br/com/caelum/vraptor/http/route/DefaultRouteBuilder.java
This PR creates a protected method in `DefaultRouteBuilder` to allow customization of the default Route implementation. This way, anyone who want to use a `Route` implementation instead of `FixedMethodStrategy` can only override this method.
- Extract route creation to a method.
=> Extract route strategy creation to protected method to allow extension

vraptor-core/src/main/java/br/com/caelum/vraptor/view/LinkToHandler.java
fixes #1077 and #1097 
This warning was introduced in one of the code quality improvement PR's 
https://github.com/caelum/vraptor4/commit/06ce603697e797c798627fd62e9e17369ffee6d7#diff-e4edbfa895ef0300e76f8ea310e334a4R158
I increase the log level to debug, just like other log messages in this file
=> updating linker logger to debug
