caelum/vraptor4

vraptor-site/content/en/docs/controllers-rest.html
vraptor-site/content/pt/docs/controllers-rest.html

Closes https://github.com/caelum/vraptor4/issues/927

improving docs about consumes with and without root

---

vraptor-core/src/main/java/br/com/caelum/vraptor/environment/DefaultEnvironment.java

don't log exception on missing environment.properties

---

vraptor-site/Gemfile.lock
vraptor-site/Rules

Removing some dead code and refactoring Rules file

---

vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/JSONSerialization.java
vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/GsonBuilderWrapper.java
vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/GsonJSONSerialization.java
vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/GsonSerializerBuilder.java
vraptor-core/src/test/java/br/com/caelum/vraptor/serialization/gson/GsonJSONSerializationTest.java
vraptor-site/content/en/docs/view-and-ajax.html
vraptor-site/content/pt/docs/trabalhando-com-a-view.html

This pull request is related to issue #984 .

Add functionality that enables serialization of null fields in json

---

vraptor-blank-project/pom-dist.xml

this PR closes #970, and closes #985. Also related with #963. Thanks to @mariofts

Fixing output dir on pom-dist.xml and updating it

---

vraptor-core/src/main/java/br/com/caelum/vraptor/core/MethodInfo.java
vraptor-core/src/test/java/br/com/caelum/vraptor/core/MethodInfoTest.java

Resseting valued params when controller method change

---

vraptor-core/src/main/java/br/com/caelum/vraptor/observer/InstantiateObserver.java

InstantiateObserver must be dependent

---

vraptor-site/content/pt/docs/componentes.html

Adding constructor for CustomPathResolver
Fix to issue #991

Fix example for CustomPathResolver

---

vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/CalendarGsonConverter.java
vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/DateGsonConverter.java
vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/MessageGsonConverter.java
vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/xstream/CalendarConverter.java
vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/xstream/MessageConverter.java
vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/xstream/NullConverter.java

closes https://github.com/caelum/vraptor4/issues/996

Gson and xstream converters as alternatives

---

vraptor-blank-project/pom.xml
vraptor-core/pom.xml
vraptor-musicjungle/pom.xml

updating iogi

---

vraptor-site/content/en/download.html
vraptor-site/content/pt/download.html

adding setupmyproject info

---

vraptor-core/src/main/java/br/com/caelum/vraptor/controller/DefaultControllerInstance.java
vraptor-core/src/test/java/br/com/caelum/vraptor/controller/DefaultControllerInstanceTest.java

this change fix the bug reported on https://github.com/caelum/vraptor4/issues/1022

Unwrapping CDI proxy on controller instance

---

vraptor-core/src/main/java/br/com/caelum/vraptor/core/DefaultResult.java
vraptor-core/src/main/java/br/com/caelum/vraptor/http/iogi/ArrayAdapter.java
vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/xstream/XStreamBuilderImpl.java
vraptor-core/src/main/java/br/com/caelum/vraptor/validator/Messages.java

This pull request is focused on resolving occurrences of rule:
pmd:RedundantFieldInitializer - Redundant Field Initializer.
You can find more information about the issue here:
http://dev.eclipse.org/sonar/rules/show/pmd:RedundantFieldInitializer
Please let me know if you have any questions.
Christian

General Code Quality Improvement

---

vraptor-core/src/main/java/br/com/caelum/vraptor/cache/LRUCacheStore.java
vraptor-core/src/main/java/br/com/caelum/vraptor/controller/DefaultControllerInstance.java
vraptor-core/src/main/java/br/com/caelum/vraptor/converter/ConversionException.java
vraptor-core/src/main/java/br/com/caelum/vraptor/core/InterceptorStackHandlersCache.java
vraptor-core/src/main/java/br/com/caelum/vraptor/environment/EnvironmentType.java
vraptor-core/src/main/java/br/com/caelum/vraptor/events/InterceptorsExecuted.java
vraptor-core/src/main/java/br/com/caelum/vraptor/events/InterceptorsReady.java
vraptor-core/src/main/java/br/com/caelum/vraptor/http/route/Invocation.java
vraptor-core/src/main/java/br/com/caelum/vraptor/http/route/PriorityRoutesList.java
vraptor-core/src/main/java/br/com/caelum/vraptor/interceptor/AspectStyleInterceptorHandler.java
vraptor-core/src/main/java/br/com/caelum/vraptor/interceptor/Graph.java
vraptor-core/src/main/java/br/com/caelum/vraptor/interceptor/TopologicalSortedInterceptorRegistry.java
vraptor-core/src/main/java/br/com/caelum/vraptor/proxy/JavassistProxifier.java
vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/Exclusions.java
vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/GsonBuilderWrapper.java
vraptor-core/src/main/java/br/com/caelum/vraptor/validator/Messages.java
vraptor-core/src/main/java/br/com/caelum/vraptor/view/LinkToHandler.java
vraptor-musicjungle/src/acceptance/java/br/com/caelum/vraptor/musicjungle/acceptance/pages/PageForm.java

This pull request is focused on resolving occurrences of Sonar rule pmd:ImmutableField - Immutable Field
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=pmd:ImmutableField
Please let me know if you have any questions.
M-Ezzat

pmd:ImmutableField - Immutable Field

---

vraptor-site/content/en/cookbook/integrating-vraptor-with-tiles3.html
vraptor-site/content/pt/cookbook/integrando-vraptor-com-tiles3.html

This is the documentation already updated.

Documentation edited to have information about old javassist version

---

vraptor-site/layouts/en/cookbook.html
vraptor-site/layouts/pt/cookbook.html

adding in cookbook menu the page #1062

adding in cookbook menu the page about @ConversationScoped

---

vraptor-site/content/en/docs/components.html
vraptor-site/content/en/docs/controllers-rest.html
vraptor-site/content/pt/docs/componentes.html

The oracle has changed the directory of your documents.

Update references to oracle docs

---

vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/GsonBuilderWrapper.java

Change class method GsonBuilderWrapper.registerAdapter to protected for possible override..

Change visibility to protected for possible override.

---

vraptor-core/src/main/java/br/com/caelum/vraptor/converter/StringConverter.java
vraptor-core/src/main/java/br/com/caelum/vraptor/http/iogi/VRaptorInstantiator.java

As discussed on this thread: https://groups.google.com/forum/#!topic/caelum-vraptor/98KzmkmDij4 I'm requesting this pull with a possible solution for issue #1072 where a custom String converter is never called.

Possible solution for issue #1072

---

vraptor-site/content/en/cookbook/using-angularjs-vraptor4.html
vraptor-site/content/pt/cookbook/utilizando-angularjs-vraptor4.html
vraptor-site/layouts/en/cookbook.html
vraptor-site/layouts/pt/cookbook.html

simple cookbook about VRaptor + AngularJS #761

create cookbook about VRaptor + AngularJS

---

vraptor-site/content/en/docs/contributing-to-vraptor.html
vraptor-site/content/en/docs/one-minute-guide.html
vraptor-site/content/en/docs/ten-minute-guide.html
vraptor-site/layouts/header.html

Remove the question link

---

vraptor-site/content/en/cookbook/integrating-vraptor-with-tagrialib.html
vraptor-site/content/pt/cookbook/integrando-vraptor-com-tagrialib.html
vraptor-site/layouts/en/cookbook.html
vraptor-site/layouts/pt/cookbook.html

Hey @Turini and @jslsolucoes, I maked the changes. Can you review?

Recipe for integrate tagria lib with vraptor 

---

vraptor-core/src/main/java/br/com/caelum/vraptor/validator/MessageList.java

implements serializable on MessageList.class

---

vraptor-core/src/main/java/br/com/caelum/vraptor/environment/DefaultEnvironment.java

updating DefaultEnvironment logger to debug

---

vraptor-core/src/main/java/br/com/caelum/vraptor/core/JstlLocalization.java
vraptor-core/src/test/java/br/com/caelum/vraptor/core/JstlLocalizationTest.java

Solves the problem described in https://github.com/caelum/vraptor4/issues/1088
Remove unnecessary session creation, also this could cause problems if google bots starts to hit you very hard.

Remove unnecessary session creation

---

vraptor-core/src/test/java/br/com/caelum/vraptor/converter/DoubleConverterTest.java
vraptor-core/src/test/java/br/com/caelum/vraptor/converter/PrimitiveDoubleConverterTest.java

Adding tests for conversions that have grouping for every 3 digits as usual in ENUS and PTBR locales

Double and PrimitiveDouble grouping converter tests

---

vraptor-core/src/main/resources/META-INF/beans.xml

Replaces PR #1108
Now works in Tomcat, Jetty and Wildfly 12

Ignoring ServletContextFactory under undertow

---

vraptor-site/content/en/docs/controllers-rest.html
vraptor-site/content/pt/docs/controllers-rest.html

improving somewhat the explanations about controller rest

Improving explanations

---

vraptor-site/content/en/docs/dependencies-and-prerequisites.html
vraptor-site/content/pt/docs/dependencias-e-pre-requisitos.html

Hi @Turini ,  How do you think I could improve the description?

adding information about possible error when you use incompatible paranamer versions 
